controller_manager:
  ros__parameters:
    update_rate: 30
    
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 30.0
    base_frame_id: base_link
    
    left_wheel_names: ["rear_left_wheel_joint", "front_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint", "front_right_wheel_joint"]
    # TODO: MUST BE UPDATED MANUALLY
    wheel_separation: 0.4135
    wheel_radius: 0.0762

    use_stamped_vel: false